name: CI Main - RoboShop User
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'db/**'
      - '.github/workflows/ci-db-main.yml'
  workflow_dispatch:

jobs:
  cicd:
    uses: wmp-nk-v1/github-reusable-workflows/.github/workflows/cicd-m.yml@main
